/**
 * Hand-authored row types mirroring `supabase/migrations` exactly (table
 * names, column names, nullability, and CHECK-constrained string unions).
 *
 * Not generated by `supabase gen types` — that requires a live database
 * connection this environment doesn't have (no local Docker/Supabase stack,
 * no restored remote project; see README's "Remaining work" section). These
 * are kept deliberately close to the migration source (each block cites the
 * file it mirrors) so a future `supabase gen types typescript` run is a
 * drop-in replacement, not a rewrite of every call site.
 */

// ---------------------------------------------------------------------------
// users (0003_users.sql)
// ---------------------------------------------------------------------------

export type Goal = "lose_weight" | "maintain" | "gain_weight" | "build_muscle" | "general_health"
export type EquipmentAccess = "none" | "home_basic" | "gym"

export interface UserRow {
  id: string
  auth_id: string
  full_name: string | null
  age: number | null
  sex: string | null
  height_cm: number | null
  weight_kg: number | null
  activity_level: string | null
  goal: Goal | null
  conditions: string | null // comma-separated tags
  daily_calorie_target: number | null
  daily_protein_target_g: number | null
  daily_water_target_glasses: number | null
  food_allergies: string | null // comma-separated
  disliked_food_tags: string | null // comma-separated
  daily_food_budget_pkr: number | null
  meals_per_day: number
  workout_days_per_week: number
  workout_session_minutes: number
  equipment_access: EquipmentAccess
  is_premium: boolean
  premium_started_at: string | null
  created_at: string
}

/** Columns a client may write via `PATCH /rest/v1/users` (RLS: own row only, UPDATE-only — see 0003_users.sql). */
export type UserProfileUpdate = Partial<Pick<UserRow, "full_name" | "age" | "sex" | "height_cm" | "weight_kg" | "activity_level" | "goal" | "conditions" | "daily_calorie_target" | "daily_protein_target_g" | "daily_water_target_glasses" | "food_allergies" | "disliked_food_tags" | "daily_food_budget_pkr" | "meals_per_day" | "workout_days_per_week" | "workout_session_minutes" | "equipment_access">>

// ---------------------------------------------------------------------------
// foods, recipes, exercises (0002_reference_tables.sql) — public read, no auth
// ---------------------------------------------------------------------------

export interface FoodRow {
  id: number
  dish_name: string
  urdu_name: string | null
  region_variant: string | null
  portion_unit: string
  portion_grams: number | null
  calories: number | null
  protein_g: number | null
  carbs_g: number | null
  fat_g: number | null
  sugar_flag: "Y" | "N"
  verified: "Y" | "N"
  glycemic_index_category: "low" | "medium" | "high" | null
}

export interface RecipeRow {
  id: number
  recipe_name: string
  urdu_name: string | null
  description: string | null
  ingredients: string
  steps: string
  calories_per_serving: number | null
  protein_g: number | null
  carbs_g: number | null
  fat_g: number | null
  sugar_flag: "Y" | "N"
  cost_pkr_per_serving: number | null
  condition_tags: string | null
}

export interface ExerciseRow {
  id: number
  exercise_name: string
  urdu_name: string | null
  category: string | null
  intensity_level: string | null
  met_value: number
  exclude_conditions: string | null
}

// ---------------------------------------------------------------------------
// food_logs / workout_logs / water_logs / weight_logs (0004_logs.sql)
// ---------------------------------------------------------------------------

export type MealSlot = "breakfast" | "lunch" | "dinner" | "snack"
export type LogSource = "manual" | "wearable" | "import"

export interface FoodLogRow {
  id: number
  user_id: string
  food_id: number | null
  client_uuid: string
  log_date: string // DATE, 'YYYY-MM-DD'
  meal_slot: MealSlot | null
  quantity: number
  calories_snapshot: number
  protein_g_snapshot: number | null
  sugar_flag_snapshot: "Y" | "N" | null
  source: LogSource
  created_at: string
}

export type FoodLogInsert = Pick<FoodLogRow, "client_uuid" | "log_date" | "quantity" | "calories_snapshot"> & Partial<Pick<FoodLogRow, "food_id" | "meal_slot" | "protein_g_snapshot" | "sugar_flag_snapshot" | "source">>

export interface WorkoutLogRow {
  id: number
  user_id: string
  exercise_id: number | null
  client_uuid: string
  log_date: string
  duration_min: number
  calories_burned: number
  source: LogSource
  created_at: string
}

export type WorkoutLogInsert = Pick<WorkoutLogRow, "client_uuid" | "log_date" | "duration_min" | "calories_burned"> & Partial<Pick<WorkoutLogRow, "exercise_id" | "source">>

export interface WaterLogRow {
  id: number
  user_id: string
  client_uuid: string
  log_date: string
  glasses_logged: number
  created_at: string
}

export type WaterLogInsert = Pick<WaterLogRow, "client_uuid" | "log_date"> & Partial<Pick<WaterLogRow, "glasses_logged">>

export interface WeightLogRow {
  id: number
  user_id: string
  log_date: string
  weight_kg: number
  source: LogSource
  created_at: string
}

export type WeightLogInsert = Pick<WeightLogRow, "log_date" | "weight_kg"> & Partial<Pick<WeightLogRow, "source">>

// ---------------------------------------------------------------------------
// garden_state / permanent_garden (0005_garden_engine.sql, garden mechanic v2)
// SELECT-only for the authenticated role — every write happens inside a
// SECURITY DEFINER function triggered by log inserts, never a direct client
// write (ADR-0024). The client only ever reads these two tables.
// ---------------------------------------------------------------------------

export type GoalType = "hydration" | "sugar_free" | "protein" | "movement" | "consistency"
export type PlantType = "mint" | "cactus" | "wheat_stalk" | "sapling" | "succulent"

export interface GardenStateRow {
  id: number
  user_id: string
  goal_type: GoalType
  plant_type: PlantType
  cycle_started_on: string
  current_stage: 0 | 1 | 2 | 3
  is_dormant_today: boolean
}

export interface PermanentGardenRow {
  id: number
  user_id: string
  plant_type: PlantType
  board_number: number
  slot_index: number
  completed_on: string
}

// ---------------------------------------------------------------------------
// ai_plans / daily_ai_usage (0007_ai_cost_control.sql)
// ---------------------------------------------------------------------------

export type PlanType = "diet" | "workout"
export type PeriodKind = "week" | "month"

export interface AiPlanRow {
  id: number
  user_id: string
  generated_at: string
  plan_type: PlanType
  period_start: string
  period_kind: PeriodKind
  regenerations_used: number
  plan_content: unknown
}

export interface DailyAiUsageRow {
  id: number
  user_id: string
  usage_date: string
  message_count: number
}

// ---------------------------------------------------------------------------
// subscriptions / payment_intents (0006_commerce.sql)
// ---------------------------------------------------------------------------

export type SubscriptionStatus = "active" | "past_due" | "canceled" | "expired"
export type PaymentIntentStatus = "pending_review" | "approved" | "rejected"
export type PaymentMethod = "jazzcash_manual" | "easypaisa_manual"

export interface SubscriptionRow {
  id: number
  user_id: string
  provider: "jazzcash" | "easypaisa" | "card" | "manual_interim"
  provider_reference: string | null
  status: SubscriptionStatus
  amount_pkr: number
  current_period_start: string
  current_period_end: string
  created_at: string
}

export interface PaymentIntentRow {
  id: number
  user_id: string
  amount_pkr: number
  method: PaymentMethod
  user_submitted_reference: string
  status: PaymentIntentStatus
  reviewed_at: string | null
  created_at: string
}
